---
- hosts: http
  become: yes
  become_user: root

  vars:
    helloworld: Meow!

  tasks:
    - name: ansible apt install apache2
      apt: 
        name: apache2
        state: present

    - name: Start the httpd service
      service: 
        name: apache2 
        state: started
        
    - name: Configure Cat App
      template:
        src: files/index.j2
        dest: /var/www/html/index.html
